### PR TITLE
Introduced image path parameter

### PR DESCRIPTION
**Pull request by shehi**
Added ```$jquery-uniform-img-path``` parameter which would enable us to dynamically/programmatically set image path for this package. This is useful especially during CI/CD tasks of large projects.

### CODE REVIEW

**Comment by shehi** [comment]
@pixelmatrix : is anyone maintaining this project?!

**Comment by pixelmatrix** [comment]
I'm not maintaining the project any longer. @fidian was for a while, but it appears he isn't anymore either.

**Comment by shehi** [comment]
At least assign someone as collaborator who can review PRs. I volunteer. :)

**Comment by shehi** [comment]
@pixelmatrix I hate to be a pain or nuisance, but I really have a project being broken because this package has hardcoded static asset paths statically. This PR makes them dynamically settable. PLEASE, either merge it and release a new patch version, OR pass the project to someone else who can actually take care of it. As I said, I can have the collaborator role for the moment until someone more qualified and available will pop up. Right now, it's a tremendous blocker. And I don't want to fork it because I am not going to develop it further - that fork will become stale and dead in no time. Please consider my request.

**Comment by pixelmatrix** [comment]
This change looks fine to me @shehi, I'm going to go ahead and merge this one. If you'd like to be a collaborator, i'm happy to add you.

**Comment by shehi** [comment]
Awesome! :) Could you be so kind to release a patch version with this?

I will check other PRs and see what can be merged or not, discuss them 
with everyone. Thanks for adding me to collaborators list.

**Comment by fidian** [comment]
It's true about what @pixelmatrix said about me.  I used to be involved in the codebase a lot and then had to part ways when projects moved on.  I left a rewrite incomplete mostly because I felt like it was a lot to change and a lot of breaking changes.  Without getting enough feedback from the original author, I didn't feel comfortable with continuing down that path, though my commits are all in a branch (v3).  Feel free to email me directly if you like with questions - fidian@rumkin.com

**Pull request merged**
