### PR TITLE
Add bower support

### PR DESCRIPTION
**Pull request by geordie--**
I just set up a bower.json file in order to offer bower support. Once you accept the pull request the plugin could be submitted to bower registry (http://bower.io/docs/creating-packages/#register)

### CODE REVIEW

**Comment by bluemanos** [comment]
+1

But last commit in that repo was at 2013 :/

**Comment by andremleblanc** [comment]
:+1:

**Comment by shehi** [comment]
+1

**Comment by shehi** [comment]
By the way, I am already using this package via Bower. Is it using it via NPM or what?

```bower info jquery.uniform``` yields all package info.

**Comment by shehi** [comment]
I will bower-ify the codebase soon. Closing this one.

**Pull request closed without merging**
